[package]
name = "minimum_ml"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["aokyut <epaperamic@gmail.com>"]
description = "Experimental Machine Learning Library"

[dependencies]
anyhow = "1.0.100"
ndarray = "0.17.2"
rand = "0.9.2"
rand_distr = "0.5.1"
serde = { version = "= 1.0.193", features = ["derive"] }
serde_json = "1.0.108"
